#!/usr/bin/env node
"use strict";

// Expands views/pages/*.html into public/, resolving:
//   <!--#var key="value"-->        page-scoped variables (stripped from output)
//   <!--#include partial="name"--> pulls in views/partials/<name>.html, recursively
//   {{key}}                        substituted from that page's own #var declarations
// No templating engine, no dependencies — same approach as watobot's build-pages.js.

const fs = require("fs");
const path = require("path");

const ROOT_DIR = path.join(__dirname, "..");
const PAGES_DIR = path.join(ROOT_DIR, "views", "pages");
const PARTIALS_DIR = path.join(ROOT_DIR, "views", "partials");
const PUBLIC_DIR = path.join(ROOT_DIR, "public");
const FUNCTIONS_DIR = path.join(ROOT_DIR, "functions");

// views/pages/<key> -> public/<value>
const PAGE_MAP = {
  "dashboard.html": "dashboard.html",
  "community-gate-keeping.html": "community/gate-keeping.html",
  "community-form.html": "community/form.html",
};

const VAR_RE = /^<!--#var\s+([a-zA-Z0-9_]+)="([^"]*)"-->\n?/;
const INCLUDE_RE = /<!--#include\s+partial="([a-zA-Z0-9_-]+)"-->/g;

function readPartial(name) {
  const file = path.join(PARTIALS_DIR, `${name}.html`);
  if (!fs.existsSync(file)) {
    throw new Error(`Partial not found: ${name} (looked in ${file})`);
  }
  return fs.readFileSync(file, "utf8").replace(/\r?\n$/, "");
}

function resolveIncludes(content, seen) {
  let result = content;
  let guard = 0;
  while (INCLUDE_RE.test(result)) {
    INCLUDE_RE.lastIndex = 0;
    result = result.replace(INCLUDE_RE, (match, name) => {
      if (seen.has(name)) {
        throw new Error(`Circular include detected for partial "${name}"`);
      }
      const nextSeen = new Set(seen);
      nextSeen.add(name);
      return resolveIncludes(readPartial(name), nextSeen);
    });
    guard += 1;
    if (guard > 50) {
      throw new Error("Include resolution did not terminate (possible cycle)");
    }
  }
  return result;
}

function extractVars(content) {
  const vars = {};
  let rest = content;
  let match;
  while ((match = rest.match(VAR_RE))) {
    vars[match[1]] = match[2];
    rest = rest.slice(match[0].length);
  }
  return {vars, rest};
}

function substitutePlaceholders(content, vars) {
  return content.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, (match, key) => (key in vars ? vars[key] : match));
}

function buildPage(pageFile) {
  const srcPath = path.join(PAGES_DIR, pageFile);
  const raw = fs.readFileSync(srcPath, "utf8");
  const {vars, rest} = extractVars(raw);
  const withIncludes = resolveIncludes(rest, new Set());
  const finalHtml = substitutePlaceholders(withIncludes, vars);

  const outRelPath = PAGE_MAP[pageFile];
  if (!outRelPath) {
    throw new Error(`No output mapping for ${pageFile}; add it to PAGE_MAP in build-pages.js`);
  }
  const outPath = path.join(PUBLIC_DIR, outRelPath);
  fs.mkdirSync(path.dirname(outPath), {recursive: true});
  fs.writeFileSync(outPath, finalHtml, "utf8");
  return outRelPath;
}

// Parses a simple KEY=VALUE .env file (no quoting/escaping support needed
// for this repo's .env files). Missing files just contribute nothing.
function parseEnvFile(file) {
  if (!fs.existsSync(file)) return {};
  const vars = {};
  for (const line of fs.readFileSync(file, "utf8").split("\n")) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (match && !line.trim().startsWith("#")) {
      vars[match[1]] = match[2];
    }
  }
  return vars;
}

// public/assets/watobot-config.js needs to match whatever Watobot instance
// functions/.env(.local) points the Functions emulator at, so the browser's
// direct-to-Watobot calls (sending the approval message, etc.) and the
// Functions emulator's calls (listMyCommunities, etc.) never disagree about
// which server they're talking to. functions/.env.local (gitignored,
// emulator-only) overrides functions/.env the same way the Functions
// emulator itself layers them.
function writeWatobotConfig() {
  const vars = {
    ...parseEnvFile(path.join(FUNCTIONS_DIR, ".env")),
    ...parseEnvFile(path.join(FUNCTIONS_DIR, ".env.local")),
  };
  const apiBase = vars.WATOBOT_API_BASE;
  if (!apiBase) {
    throw new Error("WATOBOT_API_BASE not set in functions/.env or functions/.env.local");
  }
  const outPath = path.join(PUBLIC_DIR, "assets", "watobot-config.js");
  const content =
    `// Generated by scripts/build-pages.js from functions/.env(.local)'s\n` +
    `// WATOBOT_API_BASE — do not edit directly, and do not hand-edit or\n` +
    `// commit this file; it's rebuilt on every \`npm start\`/deploy.\n` +
    `export const WATOBOT_API_BASE = ${JSON.stringify(apiBase)};\n`;
  fs.writeFileSync(outPath, content, "utf8");
  return "assets/watobot-config.js";
}

function main() {
  const written = [];
  for (const pageFile of Object.keys(PAGE_MAP)) {
    const srcPath = path.join(PAGES_DIR, pageFile);
    if (!fs.existsSync(srcPath)) {
      throw new Error(`Missing page template: ${srcPath}`);
    }
    written.push(buildPage(pageFile));
  }
  written.push(writeWatobotConfig());
  for (const rel of written) {
    console.log(`built public/${rel}`);
  }
}

main();
